# Local copy of flutter_lints 3.0.2 to avoid package resolution issues in CI.
include: tool/lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_unnecessary_containers
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - curly_braces_in_flow_control_structures
    - depend_on_referenced_packages
    - exhaustive_cases
    - library_names
    - library_prefixes
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - prefer_spread_collections
    - recursive_getters
    - slash_for_doc_comments
    - type_init_formals
    - unnecessary_const
    - unnecessary_new
    - unnecessary_this
    - use_rethrow_when_possible

analyzer:
  exclude:
    - lib/types.dart
    - example/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
